import { getServerSession } from "next-auth";
import NavbarComponent from "@/app/components/NavbarComponents";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import LogoutButton from "@/app/components/LogoutButton";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

const Dashboard = async () => {
  const session = await getServerSession(authOptions);
  return (
    <div>
      <NavbarComponent session={session} />
      <div>
        {/* <img src={session?.user.image} alt="profile" className="rounded-2xl" /> */}
        <h1>
          Selamat datang <b className="font-bold">{session?.user.name}</b>
        </h1>
        {/* <LogoutButton /> */}
      </div>
    </div>
  );
};

export default Dashboard;
